### ISSUE TITLE
Watch page - video ratio

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#2]
I'll continue tomorrow.

- On smartphone, ratio is correct
![watch](https://user-images.githubusercontent.com/23116123/36067459-0e02d3a6-0ebe-11e8-9422-d08984045823.jpg)

- On Firefox, Chrome and Safari, it is not
![capture d ecran 2018-02-10 a 23 49 18](https://user-images.githubusercontent.com/23116123/36067410-133c5a96-0ebd-11e8-8304-d05533abf8c0.png)
![capture d ecran 2018-02-10 a 23 50 21](https://user-images.githubusercontent.com/23116123/36067427-602248e8-0ebd-11e8-8bd7-522ab49b9d06.png)
![capture d ecran 2018-02-10 a 23 51 30](https://user-images.githubusercontent.com/23116123/36067428-6038ccf8-0ebd-11e8-9071-29044c29e8ad.png)

... see also when content is played:
![capture d ecran 2018-02-11 a 15 58 45](https://user-images.githubusercontent.com/23116123/36074745-a466f526-0f44-11e8-88c6-09affaaa8e48.png)

- On Opera neither, but there is the issue of the drawer menu overlapping header and page content anyway
![capture d ecran 2018-02-10 a 23 54 24](https://user-images.githubusercontent.com/23116123/36067451-d504247e-0ebd-11e8-8223-7dd750e1b9e2.png)

**Comment by nothingismagick** [comment]
I know about this, need to implement an iframe holder that is not in the flexbox scope. In progress

**Comment by nothingismagick** [comment]
This is fixed in 0.2.2
 - please confirm

**Comment by nothingismagick** [comment]
The only other issue (AFAIK) that we are having is that on iOS the iFrame loading is borked. On first load (without cookies) the iFrame shows the content. You can watch it too. However, this situation changes when you change the iFrame source. Something that Google is doing f*cks with it and game over for the Iframe.

**Comment by nothingismagick** [comment]
I am closing this, but will open a new issue about the iOS iframe problem.
