### ISSUE TITLE
scroll impossible on Firefox

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#3]
This is an issue only on Firefox.
Edit: scroll works inside the downloadable documents div (not on the page itself though)

**Comment by nothingismagick** [comment]
This might be because of the hacky way that I turned off the scrollbar handles. We need to look closer into scrolling issues. Nice catch.

```
  ::-webkit-scrollbar {
    display: none;
  }
  body {
    -ms-overflow-style: none;
    overflow: -moz-scrollbars-none;
  }
```

**Comment by minivio** [comment]
MacBook Pro (Late 2011)
MacOS v10.11.6
App v0.2.5
Firefox v58.0.2

Issue fixed
