### ISSUE TITLE
Gray background on hover menu item

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#5]
- **Safari & Chrome**: unlike other items, Language and Mining don't show any gray background when hovered with the mouse with drawer menu open (but it works with drawer menu closed).
- **Firefox & Opera**: same as Safari with drawer menu open, but impossible to tell when closed, because drawer menu is impossible to close on this browser.
![capture d ecran 2018-02-11 a 16 21 59](https://user-images.githubusercontent.com/23116123/36074981-f04407ba-0f47-11e8-94f7-d83eca9072e5.png)
![capture d ecran 2018-02-11 a 16 58 46](https://user-images.githubusercontent.com/23116123/36075275-df3bcf5c-0f4c-11e8-9306-18fa94a1b796.png)

**Comment by nothingismagick** [comment]
The icons show me you referenced this issue pre 0.2.1 - But anyway the higher-level issue is that these two fields have a different kind of interaction for the user. One hides a modal, and the other integrates the action into the sidebar. Do you think we should still color them on hover?

I am sure it is still an issue, but can you please check?

**Comment by minivio** [comment]
MacBook Pro (Late 2011)
MacOS v10.11.6
App v0.2.5
Firefox v58.0.2
Chrome v64.0.3282.167
Safari v10.0.2
Opera v51.0.2830.26

All browsers behave the same way . 
With menu closed: gray background on hover on all items.
With menu open: no gray background on Language and Mining.

I think all items should all get the same background on hover, regardless of their function. This shows you in a way that you can interact with it.
By the way, I would feel it's even more efficient if the background of the selected item in the menu gets a distinct color, not the same as the hover background. If the hover background has some transparency, it could add to the selected item's background color when this one is hovered and make a nice effect.

**Comment by nothingismagick** [comment]
go for it.

**Comment by nothingismagick** [comment]
Just remember - there is the mininav and the sidebar. You'll need to treat both of them.
