### ISSUE TITLE
Begin Mining Item in Menu

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#8]
-**Firefox**: click on Begin Mining doesn't trigger anything at all. 
-**Safari**: opens silder, but Mining stays at 0H/s
![capture d ecran 2018-02-11 a 16 35 48](https://user-images.githubusercontent.com/23116123/36075085-a407a58a-0f49-11e8-81f1-cac9a72960a4.png)
- **Chrome**: same as Safari + was slow to start (had to click several times - maybe I lacked patience).
- **Opera**: clicked once, nothing happend. Clicked a second time and mining started. Shows 5H/s (many apps open on my computer right now, might explain low rate).
- **Smartphone**: works as expected (but only gets 2H/s)

**Comment by nothingismagick** [comment]
This is definitely an issue with the old miner interface. I stopped using the native miner after v0.1

This is how it looks now. Are you sure you are on current dev branch? What version of the front end do you see? (In this screenshot you see the version number in the bottom grey bar)

![screen shot 2018-02-11 at 18 54 09](https://user-images.githubusercontent.com/35242872/36076486-0193417e-0f5d-11e8-926d-119c88915fee.png)

**Comment by nothingismagick** [comment]
Resolved in v0.2.1

**Comment by minivio** [comment]
Hi! Just tested on v0.2.1

Unfortunately, Safari & Firefox seem not to pass the Init stage.
![capture d ecran 2018-02-11 a 20 33 49](https://user-images.githubusercontent.com/23116123/36077414-e8eabe8c-0f6a-11e8-8cb7-3153c3d95ea3.png)

Safari also displays icon content outside of icon (same problem happens there with menu closed or open)
![capture d ecran 2018-02-11 a 20 37 31](https://user-images.githubusercontent.com/23116123/36077451-68df64da-0f6b-11e8-9f35-25a2b8c84011.png)

Chrome & Opera, finally, do start mining as requested 👍
